import type { Metadata } from "next";
import { Work_Sans, ZCOOL_XiaoWei } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { HeaderColorProvider } from "./context/HeaderColorContext";

const Footer = dynamic(() => import("@/components/Footer/page"), {
  loading: () => <p>Loading...</p>,
});

const Header = dynamic(() => import("@/components/Header/page"), {
  loading: () => <p>Loading...</p>,
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ["400", "500", "700"],
});

export const zcoolXiaoWei = ZCOOL_XiaoWei({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-zcool-xiaowei",
});

export const metadata: Metadata = {
  title: "Nexthikes IT Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${zcoolXiaoWei.variable} antialiased bg-white`}
      >
        <HeaderColorProvider>
          <Header />
          {children}
          <Footer />
        </HeaderColorProvider>
      </body>
    </html>
  );
}
