import { Work_Sans, ZCOOL_XiaoWei } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import ClientWrapper from "./ClientWrapper";
import { HeaderColorProvider } from "./context/HeaderColorContext";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ["400", "500", "700"],
  display: "swap",
});

export const zcoolXiaoWei = ZCOOL_XiaoWei({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-zcool-xiaowei",
});

export const metadata: Metadata = {
  title: "NextHikes IT Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${zcoolXiaoWei.variable} antialiased bg-white`}>
        <HeaderColorProvider>
          <Header />
          {children}
          <Footer />
        </HeaderColorProvider>
      </body>
    </html>
  );
}
