import { Work_Sans, ZCOOL_XiaoWei } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { HeaderColorProvider } from "./context/HeaderColorContext";
import Footer from "@/components/Footer/page";
import FloatingContactWidget from "@/components/FloatingContactWidget/page";
import { MobileMenuProvider } from "./context/MobileMenuContext";
import HeaderWrapper from "@/components/HeaderWrapper/HeaderWrapper";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ["400", "500", "700"],
  display: "swap",
});

export const zcoolXiaoWei = ZCOOL_XiaoWei({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-zcool-xiaowei",
});

export const metadata: Metadata = {
  title: "NextHikes IT Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${zcoolXiaoWei.variable} antialiased bg-white`}
      >
        <MobileMenuProvider>
          <HeaderColorProvider>
            <HeaderWrapper />
            {children}
            <Footer />
            <FloatingContactWidget />
          </HeaderColorProvider>
        </MobileMenuProvider>
      </body>
    </html>
  );
}
